export const countriesList = [ 
    {value: "Afghanistan",id: "774", label: "Afghanistan"},
    {value: "Albania",id: "775", label: "Albania"},
    {value: "Algeria",id: "776", label: "Algeria"},
    {value: "American Samoa",id: "777", label: "American Samoa"},
    {value: "Andorra",id: "778", label: "Andorra"},
    {value: "Angola",id: "779", label: "Angola"},
    {value: "Anguilla",id: "780", label: "Anguilla"},
    {value: "Antarctica",id: "781", label: "Antarctica"},
    {value: "Antigua and Barbuda",id: "782", label: "Antigua and Barbuda"},
    {value: "Argentina",id: "783", label: "Argentina"},
    {value: "Armenia",id: "784", label: "Armenia"},
    {value: "Aruba",id: "785", label: "Aruba"},
    {value: "Australia",id: "786", label: "Australia"},
    {value: "Austria",id: "787", label: "Austria"},
    {value: "Azerbaijan",id: "788", label: "Azerbaijan"},
    {value: "Bahamas",id: "789", label: "Bahamas"},
    {value: "Bahrain",id: "790", label: "Bahrain"},
    {value: "Bangladesh",id: "791", label: "Bangladesh"},
    {value: "Barbados",id: "792", label: "Barbados"},
    {value: "Belarus",id: "793", label: "Belarus"},
    {value: "Belgium",id: "794", label: "Belgium"},
    {value: "Belize",id: "795", label: "Belize"},
    {value: "Benin",id: "796", label: "Benin"},
    {value: "Bermuda",id: "797", label: "Bermuda"},
    {value: "Bhutan",id: "798", label: "Bhutan"},
    {value: "Bolivia",id: "799", label: "Bolivia"},
    {value: "Bosnia and Herzegovina",id: "800", label: "Bosnia and Herzegovina"},
    {value: "Botswana",id: "801", label: "Botswana"},
    {value: "Bouvet Island",id: "802", label: "Bouvet Island"},
    {value: "Brazil",id: "803", label: "Brazil"},
    {value: "British Indian Ocean Territory",id: "804", label: "British Indian Ocean Territory"},
    {value: "British Virgin Islands",id: "805", label: "British Virgin Islands"},
    {value: "Brunei",id: "806", label: "Brunei"},
    {value: "Bulgaria",id: "807", label: "Bulgaria"},
    {value: "Burkina Faso",id: "808", label: "Burkina Faso"},
    {value: "Burundi",id: "809", label: "Burundi"},
    {value: "Cambodia",id: "810", label: "Cambodia"},
    {value: "Cameroon",id: "811", label: "Cameroon"},
    {value: "Canada",id: "812", label: "Canada"},
    {value: "Cape Verde",id: "813", label: "Cape Verde"},
    {value: "Cayman Islands",id: "814", label: "Cayman Islands"},
    {value: "Central African Republic",id: "815", label: "Central African Republic"},
    {value: "Chad",id: "816", label: "Chad"},
    {value: "Chile",id: "817", label: "Chile"},
    {value: "China",id: "818", label: "China"},
    {value: "Christmas Island",id: "819", label: "Christmas Island"},
    {value: "Cocos [Keeling] Islands",id: "820", label: "Cocos [Keeling] Islands"},
    {value: "Colombia",id: "821", label: "Colombia"},
    {value: "Comoros",id: "822", label: "Comoros"},
    {value: "Congo [DRC]",id: "823", label: "Congo [DRC]"},
    {value: "Congo [Republic]",id: "824", label: "Congo [Republic]"},
    {value: "Cook Islands",id: "825", label: "Cook Islands"},
    {value: "Costa Rica",id: "826", label: "Costa Rica"},
    {value: "Côte d'Ivoire",id: "827", label: "Côte d'Ivoire"},
    {value: "Croatia",id: "828", label: "Croatia"},
    {value: "Cuba",id: "829", label: "Cuba"},
    {value: "Cyprus",id: "830", label: "Cyprus"},
    {value: "Czech Republic",id: "831", label: "Czech Republic"},
    {value: "Denmark",id: "832", label: "Denmark"},
    {value: "Djibouti",id: "833", label: "Djibouti"},
    {value: "Dominica",id: "834", label: "Dominica"},
    {value: "Dominican Republic",id: "835", label: "Dominican Republic"},
    {value: "Ecuador",id: "836", label: "Ecuador"},
    {value: "Egypt",id: "837", label: "Egypt"},
    {value: "El Salvador",id: "838", label: "El Salvador"},
    {value: "Equatorial Guinea",id: "839", label: "Equatorial Guinea"},
    {value: "Eritrea",id: "840", label: "Eritrea"},
    {value: "Estonia",id: "841", label: "Estonia"},
    {value: "Ethiopia",id: "842", label: "Ethiopia"},
    {value: "Falkland Islands [Islas Malvinas]",id: "843", label: "Falkland Islands [Islas Malvinas]"},
    {value: "Faroe Islands",id: "844", label: "Faroe Islands"},
    {value: "Fiji",id: "845", label: "Fiji"},
    {value: "Finland",id: "846", label: "Finland"},
    {value: "France",id: "847", label: "France"},
    {value: "French Guiana",id: "848", label: "French Guiana"},
    {value: "French Polynesia",id: "849", label: "French Polynesia"},
    {value: "French Southern Territories",id: "850", label: "French Southern Territories"},
    {value: "Gabon",id: "851", label: "Gabon"},
    {value: "Gambia",id: "852", label: "Gambia"},
    {value: "Gaza Strip",id: "853", label: "Gaza Strip"},
    {value: "Georgia",id: "854", label: "Georgia"},
    {value: "Germany",id: "855", label: "Germany"},
    {value: "Ghana",id: "856", label: "Ghana"},
    {value: "Gibraltar",id: "857", label: "Gibraltar"},
    {value: "Greece",id: "858", label: "Greece"},
    {value: "Greenland",id: "859", label: "Greenland"},
    {value: "Grenada",id: "860", label: "Grenada"},
    {value: "Guadeloupe",id: "861", label: "Guadeloupe"},
    {value: "Guam",id: "862", label: "Guam"},
    {value: "Guatemala",id: "863", label: "Guatemala"},
    {value: "Guernsey",id: "864", label: "Guernsey"},
    {value: "Guinea",id: "865", label: "Guinea"},
    {value: "Guinea-Bissau",id: "866", label: "Guinea-Bissau"},
    {value: "Guyana",id: "867", label: "Guyana"},
    {value: "Haiti",id: "868", label: "Haiti"},
    {value: "Heard Island and McDonald Islands",id: "869", label: "Heard Island and McDonald Islands"},
    {value: "Honduras",id: "870", label: "Honduras"},
    {value: "Hong Kong",id: "871", label: "Hong Kong"},
    {value: "Hungary",id: "872", label: "Hungary"},
    {value: "Iceland",id: "873", label: "Iceland"},
    {value: "India",id: "874", label: "India"},
    {value: "Indonesia",id: "875", label: "Indonesia"},
    {value: "Iran",id: "876", label: "Iran"},
    {value: "Iraq",id: "877", label: "Iraq"},
    {value: "Ireland",id: "878", label: "Ireland"},
    {value: "Isle of Man",id: "879", label: "Isle of Man"},
    {value: "Israel",id: "880", label: "Israel"},
    {value: "Italy",id: "881", label: "Italy"},
    {value: "Jamaica",id: "882", label: "Jamaica"},
    {value: "Japan",id: "883", label: "Japan"},
    {value: "Jersey",id: "884", label: "Jersey"},
    {value: "Jordan",id: "885", label: "Jordan"},
    {value: "Kazakhstan",id: "886", label: "Kazakhstan"},
    {value: "Kenya",id: "887", label: "Kenya"},
    {value: "Kiribati",id: "888", label: "Kiribati"},
    {value: "Kosovo",id: "889", label: "Kosovo"},
    {value: "Kuwait",id: "890", label: "Kuwait"},
    {value: "Kyrgyzstan",id: "891", label: "Kyrgyzstan"},
    {value: "Laos",id: "892", label: "Laos"},
    {value: "Latvia",id: "893", label: "Latvia"},
    {value: "Lebanon",id: "894", label: "Lebanon"},
    {value: "Lesotho",id: "895", label: "Lesotho"},
    {value: "Liberia",id: "896", label: "Liberia"},
    {value: "Libya",id: "897", label: "Libya"},
    {value: "Liechtenstein",id: "898", label: "Liechtenstein"},
    {value: "Lithuania",id: "899", label: "Lithuania"},
    {value: "Luxembourg",id: "900", label: "Luxembourg"},
    {value: "Macau",id: "901", label: "Macau"},
    {value: "Macedonia [FYROM]",id: "902", label: "Macedonia [FYROM]"},
    {value: "Madagascar",id: "903", label: "Madagascar"},
    {value: "Malawi",id: "904", label: "Malawi"},
    {value: "Malaysia",id: "905", label: "Malaysia"},
    {value: "Maldives",id: "906", label: "Maldives"},
    {value: "Mali",id: "907", label: "Mali"},
    {value: "Malta",id: "908", label: "Malta"},
    {value: "Marshall Islands",id: "909", label: "Marshall Islands"},
    {value: "Martinique",id: "910", label: "Martinique"},
    {value: "Mauritania",id: "911", label: "Mauritania"},
    {value: "Mauritius",id: "912", label: "Mauritius"},
    {value: "Mayotte",id: "913", label: "Mayotte"},
    {value: "Mexico",id: "914", label: "Mexico"},
    {value: "Micronesia",id: "915", label: "Micronesia"},
    {value: "Moldova",id: "916", label: "Moldova"},
    {value: "Monaco",id: "917", label: "Monaco"},
    {value: "Mongolia",id: "918", label: "Mongolia"},
    {value: "Montenegro",id: "919", label: "Montenegro"},
    {value: "Montserrat",id: "920", label: "Montserrat"},
    {value: "Morocco",id: "921", label: "Morocco"},
    {value: "Mozambique",id: "922", label: "Mozambique"},
    {value: "Myanmar [Burma]",id: "923", label: "Myanmar [Burma]"},
    {value: "Namibia",id: "924", label: "Namibia"},
    {value: "Nauru",id: "925", label: "Nauru"},
    {value: "Nepal",id: "926", label: "Nepal"},
    {value: "Netherlands",id: "927", label: "Netherlands"},
    {value: "Netherlands Antilles",id: "928", label: "Netherlands Antilles"},
    {value: "New Caledonia",id: "929", label: "New Caledonia"},
    {value: "New Zealand",id: "930", label: "New Zealand"},
    {value: "Nicaragua",id: "931", label: "Nicaragua"},
    {value: "Niger",id: "932", label: "Niger"},
    {value: "Nigeria",id: "933", label: "Nigeria"},
    {value: "Niue",id: "934", label: "Niue"},
    {value: "Norfolk Island",id: "935", label: "Norfolk Island"},
    {value: "North Korea",id: "936", label: "North Korea"},
    {value: "Northern Mariana Islands",id: "937", label: "Northern Mariana Islands"},
    {value: "Norway",id: "938", label: "Norway"},
    {value: "Oman",id: "939", label: "Oman"},
    {value: "Pakistan",id: "940", label: "Pakistan"},
    {value: "Palau",id: "941", label: "Palau"},
    {value: "Palestinian Territories",id: "942", label: "Palestinian Territories"},
    {value: "Panama",id: "943", label: "Panama"},
    {value: "Papua New Guinea",id: "944", label: "Papua New Guinea"},
    {value: "Paraguay",id: "945", label: "Paraguay"},
    {value: "Peru",id: "946", label: "Peru"},
    {value: "Philippines",id: "947", label: "Philippines"},
    {value: "Pitcairn Islands",id: "948", label: "Pitcairn Islands"},
    {value: "Poland",id: "949", label: "Poland"},
    {value: "Portugal",id: "950", label: "Portugal"},
    {value: "Puerto Rico",id: "951", label: "Puerto Rico"},
    {value: "Qatar",id: "952", label: "Qatar"},
    {value: "Réunion",id: "953", label: "Réunion"},
    {value: "Romania",id: "954", label: "Romania"},
    {value: "Russia",id: "955", label: "Russia"},
    {value: "Rwanda",id: "956", label: "Rwanda"},
    {value: "Saint Helena",id: "957", label: "Saint Helena"},
    {value: "Saint Kitts and Nevis",id: "958", label: "Saint Kitts and Nevis"},
    {value: "Saint Lucia",id: "959", label: "Saint Lucia"},
    {value: "Saint Pierre and Miquelon",id: "960", label: "Saint Pierre and Miquelon"},
    {value: "Saint Vincent and the Grenadines",id: "961", label: "Saint Vincent and the Grenadines"},
    {value: "Samoa",id: "962", label: "Samoa"},
    {value: "San Marino",id: "963", label: "San Marino"},
    {value: "São Tomé and Príncipe",id: "964", label: "São Tomé and Príncipe"},
    {value: "Saudi Arabia",id: "965", label: "Saudi Arabia"},
    {value: "Senegal",id: "966", label: "Senegal"},
    {value: "Serbia",id: "967", label: "Serbia"},
    {value: "Seychelles",id: "968", label: "Seychelles"},
    {value: "Sierra Leone",id: "969", label: "Sierra Leone"},
    {value: "Singapore",id: "970", label: "Singapore"},
    {value: "Slovakia",id: "971", label: "Slovakia"},
    {value: "Slovenia",id: "972", label: "Slovenia"},
    {value: "Solomon Islands",id: "973", label: "Solomon Islands"},
    {value: "Somalia",id: "974", label: "Somalia"},
    {value: "South Africa",id: "975", label: "South Africa"},
    {value: "South Georgia and the South Sandwich Islands",id: "976", label: "South Georgia and the South Sandwich Islands"},
    {value: "South Korea",id: "977", label: "South Korea"},
    {value: "Spain",id: "978", label: "Spain"},
    {value: "Sri Lanka",id: "979", label: "Sri Lanka"},
    {value: "Sudan",id: "980", label: "Sudan"},
    {value: "Surivalue",id: "981", label: "Surilabel"},
    {value: "Svalbard and Jan Mayen",id: "982", label: "Svalbard and Jan Mayen"},
    {value: "Swaziland",id: "983", label: "Swaziland"},
    {value: "Sweden",id: "984", label: "Sweden"},
    {value: "Switzerland",id: "985", label: "Switzerland"},
    {value: "Syria",id: "986", label: "Syria"},
    {value: "Taiwan",id: "987", label: "Taiwan"},
    {value: "Tajikistan",id: "988", label: "Tajikistan"},
    {value: "Tanzania",id: "989", label: "Tanzania"},
    {value: "Thailand",id: "990", label: "Thailand"},
    {value: "Timor-Leste",id: "991", label: "Timor-Leste"},
    {value: "Togo",id: "992", label: "Togo"},
    {value: "Tokelau",id: "993", label: "Tokelau"},
    {value: "Tonga",id: "994", label: "Tonga"},
    {value: "Trinidad and Tobago",id: "995", label: "Trinidad and Tobago"},
    {value: "Tunisia",id: "996", label: "Tunisia"},
    {value: "Turkey",id: "997", label: "Turkey"},
    {value: "Turkmenistan",id: "998", label: "Turkmenistan"},
    {value: "Turks and Caicos Islands",id: "999", label: "Turks and Caicos Islands"},
    {value: "Tuvalu",id: "1000", label: "Tuvalu",},
    {value: "U.S. Minor Outlying Islands",id: "1001", label: "U.S. Minor Outlying Islands",},
    {value: "U.S. Virgin Islands",id: "1002", label: "U.S. Virgin Islands",},
    {value: "Uganda",id: "1003", label: "Uganda",},
    {value: "Ukraine",id: "1004", label: "Ukraine",},
    {value: "United Arab Emirates",id: "1005", label: "United Arab Emirates",},
    {value: "United Kingdom",id: "1006", label: "United Kingdom",},
    {value: "United States",id: "1007", label: "United States",},
    {value: "Uruguay",id: "1008", label: "Uruguay",},
    {value: "Uzbekistan",id: "1009", label: "Uzbekistan",},
    {value: "Vanuatu",id: "1010", label: "Vanuatu",},
    {value: "Vatican City",id: "1011", label: "Vatican City",},
    {value: "Venezuela",id: "1012", label: "Venezuela",},
    {value: "Vietnam",id: "1013", label: "Vietnam",},
    {value: "Wallis and Futuna",id: "1014", label: "Wallis and Futuna",},
    {value: "Western Sahara",id: "1015", label: "Western Sahara",},
    {value: "Yemen",id: "1016", label: "Yemen",},
    {value: "Zambia",id: "1017", label: "Zambia",},
    {value: "Zimbabwe",id: "1018", label: "Zimbabwe",},
]

export const Regions = [
    {value: "Africa",id: "760"},
    {value: "Asia",id: "761"},
    {value: "Australia",id: "762"},
    {value: "Europe",id: "763"},
    {value: "North America",id: "764"},
    {value: "South America",id: "765"},
    {value: "Asia Pacific",id: "766"},
    {value: "DACH",id: "767"},
    {value: "EEA",id: "768"},
    {value: "EMEA",id: "769"},
    {value: "Africa Only",id: "770"},
    {value: "Canada Only",id: "771"},
    {value: "Europe Only",id: "772"},
    {value: "USA Only",id: "773"},
]