export const Countries = [ 
    {name: "Afghanistan",id: "LU"},
    {name: "Albania",id: "DE"},
    {name: "Algeria",id: "IT"},
    {name: "American Samoa",id: "FR"},
    {name: "Andorra",id: "FI"},
    {name: "Angola",id: "SE"},
    {name: "Anguilla",id: "AT"},
    {name: "Antarctica",id: "CH"},
    {name: "Antigua and Barbuda",id: "ZA"},
    {name: "Argentina",id: "AD"},
    {name: "Armenia",id: "AE"},
    {name: "Aruba",id: "AF"},
    {name: "Australia",id: "AG"},
    {name: "Austria",id: "AI"},
    {name: "Azerbaijan",id: "AL"},
    {name: "Bahamas",id: "AM"},
    {name: "Bahrain",id: "AN"},
    {name: "Bangladesh",id: "AO"},
    {name: "Barbados",id: "AQ"},
    {name: "Belarus",id: "AR"},
    {name: "Belgium",id: "AS"},
    {name: "Belize",id: "AU"},
    {name: "Benin",id: "AW"},
    {name: "Bermuda",id: "AZ"},
    {name: "Bhutan",id: "BA"},
    {name: "Bolivia",id: "BB"},
    {name: "Bosnia and Herzegovina",id: "BD"},
    {name: "Botswana",id: "BE"},
    {name: "Bouvet Island",id: "BF"},
    {name: "Brazil",id: "BG"},
    {name: "British Indian Ocean Territory",id: "BH"},
    {name: "British Virgin Islands",id: "BI"},
    {name: "Brunei",id: "BJ"},
    {name: "Bulgaria",id: "BM"},
    {name: "Burkina Faso",id: "BN"},
    {name: "Burundi",id: "BO"},
    {name: "Cambodia",id: "BR"},
    {name: "Cameroon",id: "BS"},
    {name: "Canada",id: "BT"},
    {name: "Cape Verde",id: "BV"},
    {name: "Cayman Islands",id: "BW"},
    {name: "Central African Republic",id: "BY"},
    {name: "Chad",id: "BZ"},
    {name: "Chile",id: "CA"},
    {name: "China",id: "CC"},
    {name: "Christmas Island",id: "CD"},
    {name: "Cocos [Keeling] Islands",id: "CF"},
    {name: "Colombia",id: "CG"},
    {name: "Comoros",id: "CI"},
    {name: "Congo [DRC]",id: "CK"},
    {name: "Congo [Republic]",id: "CL"},
    {name: "Cook Islands",id: "CM"},
    {name: "Costa Rica",id: "CN"},
    {name: "Côte d'Ivoire",id: "CO"},
    {name: "Croatia",id: "CR"},
    {name: "Cuba",id: "CU"},
    {name: "Cyprus",id: "CV"},
    {name: "Czech Republic",id: "CX"},
    {name: "Denmark",id: "CY"},
    {name: "Djibouti",id: "CZ"},
    {name: "Dominica",id: "DJ"},
    {name: "Dominican Republic",id: "DK"},
    {name: "Ecuador",id: "DM"},
    {name: "Egypt",id: "DO"},
    {name: "El Salvador",id: "DZ"},
    {name: "Equatorial Guinea",id: "EC"},
    {name: "Eritrea",id: "EE"},
    {name: "Estonia",id: "EG"},
    {name: "Ethiopia",id: "EH"},
    {name: "Falkland Islands [Islas Malvinas]",id: "ER"},
    {name: "Faroe Islands",id: "ES"},
    {name: "Fiji",id: "ET"},
    {name: "Finland",id: "FJ"},
    {name: "France",id: "FK"},
    {name: "French Guiana",id: "FM"},
    {name: "French Polynesia",id: "FO"},
    {name: "French Southern Territories",id: "GA"},
    {name: "Gabon",id: "GB"},
    {name: "Gambia",id: "GD"},
    {name: "Gaza Strip",id: "GE"},
    {name: "Georgia",id: "GF"},
    {name: "Germany",id: "GG"},
    {name: "Ghana",id: "GH"},
    {name: "Gibraltar",id: "GI"},
    {name: "Greece",id: "GL"},
    {name: "Greenland",id: "GM"},
    {name: "Grenada",id: "GN"},
    {name: "Guadeloupe",id: "GP"},
    {name: "Guam",id: "GQ"},
    {name: "Guatemala",id: "GR"},
    {name: "Guernsey",id: "GS"},
    {name: "Guinea",id: "GT"},
    {name: "Guinea-Bissau",id: "GU"},
    {name: "Guyana",id: "GW"},
    {name: "Haiti",id: "GY"},
    {name: "Heard Island and McDonald Islands",id: "GZ"},
    {name: "Honduras",id: "HK"},
    {name: "Hong Kong",id: "HM"},
    {name: "Hungary",id: "HN"},
    {name: "Iceland",id: "HR"},
    {name: "India",id: "HT"},
    {name: "Indonesia",id: "HU"},
    {name: "Iran",id: "ID"},
    {name: "Iraq",id: "IE"},
    {name: "Ireland",id: "IL"},
    {name: "Isle of Man",id: "IM"},
    {name: "Israel",id: "IN"},
    {name: "Italy",id: "IO"},
    {name: "Jamaica",id: "IQ"},
    {name: "Japan",id: "IR"},
    {name: "Jersey",id: "IS"},
    {name: "Jordan",id: "JE"},
    {name: "Kazakhstan",id: "JM"},
    {name: "Kenya",id: "JO"},
    {name: "Kiribati",id: "JP"},
    {name: "Kosovo",id: "KE"},
    {name: "Kuwait",id: "KG"},
    {name: "Kyrgyzstan",id: "KH"},
    {name: "Laos",id: "KI"},
    {name: "Latvia",id: "KM"},
    {name: "Lebanon",id: "KN"},
    {name: "Lesotho",id: "KP"},
    {name: "Liberia",id: "KR"},
    {name: "Libya",id: "KW"},
    {name: "Liechtenstein",id: "KY"},
    {name: "Lithuania",id: "KZ"},
    {name: "Luxembourg",id: "LA"},
    {name: "Macau",id: "LB"},
    {name: "Macedonia",id: "LC"},
    {name: "Madagascar",id: "LI"},
    {name: "Malawi",id: "LK"},
    {name: "Malaysia",id: "LR"},
    {name: "Maldives",id: "LS"},
    {name: "Mali",id: "LT"},
    {name: "Malta",id: "LV"},
    {name: "Marshall Islands",id: "LY"},
    {name: "Martinique",id: "MA"},
    {name: "Mauritania",id: "MC"},
    {name: "Mauritius",id: "MD"},
    {name: "Mayotte",id: "ME"},
    {name: "Mexico",id: "MG"},
    {name: "Micronesia",id: "MH"},
    {name: "Moldova",id: "MK"},
    {name: "Monaco",id: "ML"},
    {name: "Mongolia",id: "MM"},
    {name: "Montenegro",id: "MN"},
    {name: "Montserrat",id: "MO"},
    {name: "Morocco",id: "MP"},
    {name: "Mozambique",id: "MQ"},
    {name: "Myanmar [Burma]",id: "MR"},
    {name: "Namibia",id: "MS"},
    {name: "Nauru",id: "MT"},
    {name: "Nepal",id: "MU"},
    {name: "Netherlands",id: "MV"},
    {name: "Netherlands Antilles",id: "MW"},
    {name: "New Caledonia",id: "MX"},
    {name: "New Zealand",id: "MY"},
    {name: "Nicaragua",id: "MZ"},
    {name: "Niger",id: "NA"},
    {name: "Nigeria",id: "NC"},
    {name: "Niue",id: "NE"},
    {name: "Norfolk Island",id: "NF"},
    {name: "North Korea",id: "NG"},
    {name: "Northern Mariana Islands",id: "NI"},
    {name: "Norway",id: "NL"},
    {name: "Oman",id: "NO"},
    {name: "Pakistan",id: "NP"},
    {name: "Palau",id: "NR"},
    {name: "Palestinian Territories",id: "NU"},
    {name: "Panama",id: "NZ"},
    {name: "Papua New Guinea",id: "OM"},
    {name: "Paraguay",id: "PA"},
    {name: "Peru",id: "PE"},
    {name: "Philippines",id: "PF"},
    {name: "Pitcairn Islands",id: "PG"},
    {name: "Poland",id: "PH"},
    {name: "Portugal",id: "PK"},
    {name: "Puerto Rico",id: "PL"},
    {name: "Qatar",id: "PM"},
    {name: "Réunion",id: "PN"},
    {name: "Romania",id: "PR"},
    {name: "Russia",id: "PS"},
    {name: "Rwanda",id: "PT"},
    {name: "Saint Helena",id: "PW"},
    {name: "Saint Kitts and Nevis",id: "PY"},
    {name: "Saint Lucia",id: "QA"},
    {name: "Saint Pierre and Miquelon",id: "RE"},
    {name: "Saint Vincent and the Grenadines",id: "RO"},
    {name: "Samoa",id: "RS"},
    {name: "San Marino",id: "RU"},
    {name: "São Tomé and Príncipe",id: "RW"},
    {name: "Saudi Arabia",id: "SA"},
    {name: "Senegal",id: "SB"},
    {name: "Serbia",id: "SC"},
    {name: "Seychelles",id: "SD"},
    {name: "Sierra Leone",id: "SG"},
    {name: "Singapore",id: "SH"},
    {name: "Slovakia",id: "SI"},
    {name: "Slovenia",id: "SJ"},
    {name: "Solomon Islands",id: "SK"},
    {name: "Somalia",id: "SL"},
    {name: "South Africa",id: "SM"},
    {name: "South Georgia and the South Sandwich Islands",id: "SN"},
    {name: "South Korea",id: "SO"},
    {name: "Spain",id: "SR"},
    {name: "Sri Lanka",id: "ST"},
    {name: "Sudan",id: "SV"},
    {name: "Suriname",id: "SY"},
    {name: "Svalbard and Jan Mayen",id: "SZ"},
    {name: "Swaziland",id: "TC"},
    {name: "Sweden",id: "TD"},
    {name: "Switzerland",id: "TF"},
    {name: "Syria",id: "TG"},
    {name: "Taiwan",id: "TH"},
    {name: "Tajikistan",id: "TJ"},
    {name: "Tanzania",id: "TK"},
    {name: "Thailand",id: "TL"},
    {name: "Timor-Leste",id: "TM"},
    {name: "Togo",id: "TN"},
    {name: "Tokelau",id: "TO"},
    {name: "Tonga",id: "TR"},
    {name: "Trinidad and Tobago",id: "TT"},
    {name: "Tunisia",id: "TV"},
    {name: "Turkey",id: "TW"},
    {name: "Turkmenistan",id: "TZ"},
    {name: "Turks and Caicos Islands",id: "UA"},
    {name: "Tuvalu",id: "UG"},
    {name: "U.S. Minor Outlying Islands",id: "UM"},
    {name: "U.S. Virgin Islands",id: "US"},
    {name: "Uganda",id: "UY"},
    {name: "Ukraine",id: "UZ"},
    {name: "United Arab Emirates",id: "VA"},
    {name: "United Kingdom",id: "VC"},
    {name: "United States",id: "VE"},
    {name: "Uruguay",id: "VG"},
    {name: "Uzbekistan",id: "VI"},
    {name: "Vanuatu",id: "VN"},
    {name: "Vatican City",id: "VU"},
    {name: "Venezuela",id: "WF"},
    {name: "Vietnam",id: "WS"},
    {name: "Wallis and Futuna",id: "XK"},
    {name: "Western Sahara",id: "YE"},
    {name: "Yemen",id: "YT"},
    {name: "Zambia",id: "ZM"},
    {name: "Zimbabwe",id: "ZW"},
]

export const Regions = [
    {name: "Africa",id: "Africa"},
    {name: "Asia",id: "Asia"},
    {name: "Asia Pacific",id: "Asia Pacific"},
    {name: "DACH",id: "DACH"},
    {name: "EEA",id: "EEA"},
    {name: "EMEA",id: "EMEA"},
    {name: "Europe Only",id: "Europe Only"},
    {name: "Latin America",id: "Latin America"},
    {name: "Nordics",id: "Nordics"},
    {name: "North America",id: "North America"},
    {name: "South Asia Pacific",id: "South Asia Pacific"},
    {name: "USA Only",id: "USA Only"},
]