export const Countries = [ 
    {name: "Afghanistan",id: "774"},
    {name: "Albania",id: "775"},
    {name: "Algeria",id: "776"},
    {name: "American Samoa",id: "777"},
    {name: "Andorra",id: "778"},
    {name: "Angola",id: "779"},
    {name: "Anguilla",id: "780"},
    {name: "Antarctica",id: "781"},
    {name: "Antigua and Barbuda",id: "782"},
    {name: "Argentina",id: "783"},
    {name: "Armenia",id: "784"},
    {name: "Aruba",id: "785"},
    {name: "Australia",id: "786"},
    {name: "Austria",id: "787"},
    {name: "Azerbaijan",id: "788"},
    {name: "Bahamas",id: "789"},
    {name: "Bahrain",id: "790"},
    {name: "Bangladesh",id: "791"},
    {name: "Barbados",id: "792"},
    {name: "Belarus",id: "793"},
    {name: "Belgium",id: "794"},
    {name: "Belize",id: "795"},
    {name: "Benin",id: "796"},
    {name: "Bermuda",id: "797"},
    {name: "Bhutan",id: "798"},
    {name: "Bolivia",id: "799"},
    {name: "Bosnia and Herzegovina",id: "800"},
    {name: "Botswana",id: "801"},
    {name: "Bouvet Island",id: "802"},
    {name: "Brazil",id: "803"},
    {name: "British Indian Ocean Territory",id: "804"},
    {name: "British Virgin Islands",id: "805"},
    {name: "Brunei",id: "806"},
    {name: "Bulgaria",id: "807"},
    {name: "Burkina Faso",id: "808"},
    {name: "Burundi",id: "809"},
    {name: "Cambodia",id: "810"},
    {name: "Cameroon",id: "811"},
    {name: "Canada",id: "812"},
    {name: "Cape Verde",id: "813"},
    {name: "Cayman Islands",id: "814"},
    {name: "Central African Republic",id: "815"},
    {name: "Chad",id: "816"},
    {name: "Chile",id: "817"},
    {name: "China",id: "818"},
    {name: "Christmas Island",id: "819"},
    {name: "Cocos [Keeling] Islands",id: "820"},
    {name: "Colombia",id: "821"},
    {name: "Comoros",id: "822"},
    {name: "Congo [DRC]",id: "823"},
    {name: "Congo [Republic]",id: "824"},
    {name: "Cook Islands",id: "825"},
    {name: "Costa Rica",id: "826"},
    {name: "Côte d'Ivoire",id: "827"},
    {name: "Croatia",id: "828"},
    {name: "Cuba",id: "829"},
    {name: "Cyprus",id: "830"},
    {name: "Czech Republic",id: "831"},
    {name: "Denmark",id: "832"},
    {name: "Djibouti",id: "833"},
    {name: "Dominica",id: "834"},
    {name: "Dominican Republic",id: "835"},
    {name: "Ecuador",id: "836"},
    {name: "Egypt",id: "837"},
    {name: "El Salvador",id: "838"},
    {name: "Equatorial Guinea",id: "839"},
    {name: "Eritrea",id: "840"},
    {name: "Estonia",id: "841"},
    {name: "Ethiopia",id: "842"},
    {name: "Falkland Islands [Islas Malvinas]",id: "843"},
    {name: "Faroe Islands",id: "844"},
    {name: "Fiji",id: "845"},
    {name: "Finland",id: "846"},
    {name: "France",id: "847"},
    {name: "French Guiana",id: "848"},
    {name: "French Polynesia",id: "849"},
    {name: "French Southern Territories",id: "850"},
    {name: "Gabon",id: "851"},
    {name: "Gambia",id: "852"},
    {name: "Gaza Strip",id: "853"},
    {name: "Georgia",id: "854"},
    {name: "Germany",id: "855"},
    {name: "Ghana",id: "856"},
    {name: "Gibraltar",id: "857"},
    {name: "Greece",id: "858"},
    {name: "Greenland",id: "859"},
    {name: "Grenada",id: "860"},
    {name: "Guadeloupe",id: "861"},
    {name: "Guam",id: "862"},
    {name: "Guatemala",id: "863"},
    {name: "Guernsey",id: "864"},
    {name: "Guinea",id: "865"},
    {name: "Guinea-Bissau",id: "866"},
    {name: "Guyana",id: "867"},
    {name: "Haiti",id: "868"},
    {name: "Heard Island and McDonald Islands",id: "869"},
    {name: "Honduras",id: "870"},
    {name: "Hong Kong",id: "871"},
    {name: "Hungary",id: "872"},
    {name: "Iceland",id: "873"},
    {name: "India",id: "874"},
    {name: "Indonesia",id: "875"},
    {name: "Iran",id: "876"},
    {name: "Iraq",id: "877"},
    {name: "Ireland",id: "878"},
    {name: "Isle of Man",id: "879"},
    {name: "Israel",id: "880"},
    {name: "Italy",id: "881"},
    {name: "Jamaica",id: "882"},
    {name: "Japan",id: "883"},
    {name: "Jersey",id: "884"},
    {name: "Jordan",id: "885"},
    {name: "Kazakhstan",id: "886"},
    {name: "Kenya",id: "887"},
    {name: "Kiribati",id: "888"},
    {name: "Kosovo",id: "889"},
    {name: "Kuwait",id: "890"},
    {name: "Kyrgyzstan",id: "891"},
    {name: "Laos",id: "892"},
    {name: "Latvia",id: "893"},
    {name: "Lebanon",id: "894"},
    {name: "Lesotho",id: "895"},
    {name: "Liberia",id: "896"},
    {name: "Libya",id: "897"},
    {name: "Liechtenstein",id: "898"},
    {name: "Lithuania",id: "899"},
    {name: "Luxembourg",id: "900"},
    {name: "Macau",id: "901"},
    {name: "Macedonia [FYROM]",id: "902"},
    {name: "Madagascar",id: "903"},
    {name: "Malawi",id: "904"},
    {name: "Malaysia",id: "905"},
    {name: "Maldives",id: "906"},
    {name: "Mali",id: "907"},
    {name: "Malta",id: "908"},
    {name: "Marshall Islands",id: "909"},
    {name: "Martinique",id: "910"},
    {name: "Mauritania",id: "911"},
    {name: "Mauritius",id: "912"},
    {name: "Mayotte",id: "913"},
    {name: "Mexico",id: "914"},
    {name: "Micronesia",id: "915"},
    {name: "Moldova",id: "916"},
    {name: "Monaco",id: "917"},
    {name: "Mongolia",id: "918"},
    {name: "Montenegro",id: "919"},
    {name: "Montserrat",id: "920"},
    {name: "Morocco",id: "921"},
    {name: "Mozambique",id: "922"},
    {name: "Myanmar [Burma]",id: "923"},
    {name: "Namibia",id: "924"},
    {name: "Nauru",id: "925"},
    {name: "Nepal",id: "926"},
    {name: "Netherlands",id: "927"},
    {name: "Netherlands Antilles",id: "928"},
    {name: "New Caledonia",id: "929"},
    {name: "New Zealand",id: "930"},
    {name: "Nicaragua",id: "931"},
    {name: "Niger",id: "932"},
    {name: "Nigeria",id: "933"},
    {name: "Niue",id: "934"},
    {name: "Norfolk Island",id: "935"},
    {name: "North Korea",id: "936"},
    {name: "Northern Mariana Islands",id: "937"},
    {name: "Norway",id: "938"},
    {name: "Oman",id: "939"},
    {name: "Pakistan",id: "940"},
    {name: "Palau",id: "941"},
    {name: "Palestinian Territories",id: "942"},
    {name: "Panama",id: "943"},
    {name: "Papua New Guinea",id: "944"},
    {name: "Paraguay",id: "945"},
    {name: "Peru",id: "946"},
    {name: "Philippines",id: "947"},
    {name: "Pitcairn Islands",id: "948"},
    {name: "Poland",id: "949"},
    {name: "Portugal",id: "950"},
    {name: "Puerto Rico",id: "951"},
    {name: "Qatar",id: "952"},
    {name: "Réunion",id: "953"},
    {name: "Romania",id: "954"},
    {name: "Russia",id: "955"},
    {name: "Rwanda",id: "956"},
    {name: "Saint Helena",id: "957"},
    {name: "Saint Kitts and Nevis",id: "958"},
    {name: "Saint Lucia",id: "959"},
    {name: "Saint Pierre and Miquelon",id: "960"},
    {name: "Saint Vincent and the Grenadines",id: "961"},
    {name: "Samoa",id: "962"},
    {name: "San Marino",id: "963"},
    {name: "São Tomé and Príncipe",id: "964"},
    {name: "Saudi Arabia",id: "965"},
    {name: "Senegal",id: "966"},
    {name: "Serbia",id: "967"},
    {name: "Seychelles",id: "968"},
    {name: "Sierra Leone",id: "969"},
    {name: "Singapore",id: "970"},
    {name: "Slovakia",id: "971"},
    {name: "Slovenia",id: "972"},
    {name: "Solomon Islands",id: "973"},
    {name: "Somalia",id: "974"},
    {name: "South Africa",id: "975"},
    {name: "South Georgia and the South Sandwich Islands",id: "976"},
    {name: "South Korea",id: "977"},
    {name: "Spain",id: "978"},
    {name: "Sri Lanka",id: "979"},
    {name: "Sudan",id: "980"},
    {name: "Suriname",id: "981"},
    {name: "Svalbard and Jan Mayen",id: "982"},
    {name: "Swaziland",id: "983"},
    {name: "Sweden",id: "984"},
    {name: "Switzerland",id: "985"},
    {name: "Syria",id: "986"},
    {name: "Taiwan",id: "987"},
    {name: "Tajikistan",id: "988"},
    {name: "Tanzania",id: "989"},
    {name: "Thailand",id: "990"},
    {name: "Timor-Leste",id: "991"},
    {name: "Togo",id: "992"},
    {name: "Tokelau",id: "993"},
    {name: "Tonga",id: "994"},
    {name: "Trinidad and Tobago",id: "995"},
    {name: "Tunisia",id: "996"},
    {name: "Turkey",id: "997"},
    {name: "Turkmenistan",id: "998"},
    {name: "Turks and Caicos Islands",id: "999"},
    {name: "Tuvalu",id: "1000"},
    {name: "U.S. Minor Outlying Islands",id: "1001"},
    {name: "U.S. Virgin Islands",id: "1002"},
    {name: "Uganda",id: "1003"},
    {name: "Ukraine",id: "1004"},
    {name: "United Arab Emirates",id: "1005"},
    {name: "United Kingdom",id: "1006"},
    {name: "United States",id: "1007"},
    {name: "Uruguay",id: "1008"},
    {name: "Uzbekistan",id: "1009"},
    {name: "Vanuatu",id: "1010"},
    {name: "Vatican City",id: "1011"},
    {name: "Venezuela",id: "1012"},
    {name: "Vietnam",id: "1013"},
    {name: "Wallis and Futuna",id: "1014"},
    {name: "Western Sahara",id: "1015"},
    {name: "Yemen",id: "1016"},
    {name: "Zambia",id: "1017"},
    {name: "Zimbabwe",id: "1018"},
]

export const Regions = [
    {name: "Africa",id: "760"},
    {name: "Asia",id: "761"},
    {name: "Australia",id: "762"},
    {name: "Europe",id: "763"},
    {name: "North America",id: "764"},
    {name: "South America",id: "765"},
    {name: "Asia Pacific",id: "766"},
    {name: "DACH",id: "767"},
    {name: "EEA",id: "768"},
    {name: "EMEA",id: "769"},
    {name: "Africa Only",id: "770"},
    {name: "Canada Only",id: "771"},
    {name: "Europe Only",id: "772"},
    {name: "USA Only",id: "773"},
]