export const Countries = [ 
    {name: "Afghanistan",id: "515"},
    {name: "Albania",id: "516"},
    {name: "Algeria",id: "517"},
    {name: "American Samoa",id: "518"},
    {name: "Andorra",id: "519"},
    {name: "Angola",id: "520"},
    {name: "Anguilla",id: "521"},
    {name: "Antarctica",id: "522"},
    {name: "Antigua and Barbuda",id: "523"},
    {name: "Argentina",id: "524"},
    {name: "Armenia",id: "525"},
    {name: "Aruba",id: "526"},
    {name: "Australia",id: "527"},
    {name: "Austria",id: "528"},
    {name: "Azerbaijan",id: "529"},
    {name: "Bahamas",id: "530"},
    {name: "Bahrain",id: "531"},
    {name: "Bangladesh",id: "532"},
    {name: "Barbados",id: "533"},
    {name: "Belarus",id: "534"},
    {name: "Belgium",id: "535"},
    {name: "Belize",id: "536"},
    {name: "Benin",id: "537"},
    {name: "Bermuda",id: "538"},
    {name: "Bhutan",id: "539"},
    {name: "Bolivia",id: "540"},
    {name: "Bosnia and Herzegovina",id: "541"},
    {name: "Botswana",id: "542"},
    {name: "Bouvet Island",id: "543"},
    {name: "Brazil",id: "544"},
    {name: "British Indian Ocean Territory",id: "545"},
    {name: "British Virgin Islands",id: "546"},
    {name: "Brunei",id: "547"},
    {name: "Bulgaria",id: "548"},
    {name: "Burkina Faso",id: "549"},
    {name: "Burundi",id: "550"},
    {name: "Cambodia",id: "551"},
    {name: "Cameroon",id: "552"},
    {name: "Canada",id: "553"},
    {name: "Cape Verde",id: "554"},
    {name: "Cayman Islands",id: "555"},
    {name: "Central African Republic",id: "556"},
    {name: "Chad",id: "557"},
    {name: "Chile",id: "558"},
    {name: "China",id: "559"},
    {name: "Christmas Island",id: "560"},
    {name: "Cocos [Keeling] Islands",id: "561"},
    {name: "Colombia",id: "562"},
    {name: "Comoros",id: "563"},
    {name: "Congo [DRC]",id: "564"},
    {name: "Congo [Republic]",id: "565"},
    {name: "Cook Islands",id: "566"},
    {name: "Costa Rica",id: "567"},
    {name: "Côte d'Ivoire",id: "568"},
    {name: "Croatia",id: "569"},
    {name: "Cuba",id: "570"},
    {name: "Cyprus",id: "571"},
    {name: "Czech Republic",id: "572"},
    {name: "Denmark",id: "573"},
    {name: "Djibouti",id: "574"},
    {name: "Dominica",id: "575"},
    {name: "Dominican Republic",id: "576"},
    {name: "Ecuador",id: "577"},
    {name: "Egypt",id: "578"},
    {name: "El Salvador",id: "579"},
    {name: "Equatorial Guinea",id: "580"},
    {name: "Eritrea",id: "581"},
    {name: "Estonia",id: "582"},
    {name: "Ethiopia",id: "583"},
    {name: "Falkland Islands [Islas Malvinas]",id: "584"},
    {name: "Faroe Islands",id: "585"},
    {name: "Fiji",id: "586"},
    {name: "Finland",id: "587"},
    {name: "France",id: "588"},
    {name: "French Guiana",id: "589"},
    {name: "French Polynesia",id: "590"},
    {name: "French Southern Territories",id: "591"},
    {name: "Gabon",id: "592"},
    {name: "Gambia",id: "593"},
    {name: "Gaza Strip",id: "594"},
    {name: "Georgia",id: "595"},
    {name: "Germany",id: "596"},
    {name: "Ghana",id: "597"},
    {name: "Gibraltar",id: "598"},
    {name: "Greece",id: "599"},
    {name: "Greenland",id: "600"},
    {name: "Grenada",id: "601"},
    {name: "Guadeloupe",id: "602"},
    {name: "Guam",id: "603"},
    {name: "Guatemala",id: "604"},
    {name: "Guernsey",id: "605"},
    {name: "Guinea",id: "606"},
    {name: "Guinea-Bissau",id: "607"},
    {name: "Guyana",id: "608"},
    {name: "Haiti",id: "609"},
    {name: "Heard Island and McDonald Islands",id: "610"},
    {name: "Honduras",id: "611"},
    {name: "Hong Kong",id: "612"},
    {name: "Hungary",id: "613"},
    {name: "Iceland",id: "614"},
    {name: "India",id: "615"},
    {name: "Indonesia",id: "616"},
    {name: "Iran",id: "617"},
    {name: "Iraq",id: "618"},
    {name: "Ireland",id: "619"},
    {name: "Isle of Man",id: "620"},
    {name: "Israel",id: "621"},
    {name: "Italy",id: "622"},
    {name: "Jamaica",id: "623"},
    {name: "Japan",id: "624"},
    {name: "Jersey",id: "625"},
    {name: "Jordan",id: "626"},
    {name: "Kazakhstan",id: "627"},
    {name: "Kenya",id: "628"},
    {name: "Kiribati",id: "629"},
    {name: "Kosovo",id: "630"},
    {name: "Kuwait",id: "631"},
    {name: "Kyrgyzstan",id: "632"},
    {name: "Laos",id: "633"},
    {name: "Latvia",id: "634"},
    {name: "Lebanon",id: "635"},
    {name: "Lesotho",id: "636"},
    {name: "Liberia",id: "637"},
    {name: "Libya",id: "638"},
    {name: "Liechtenstein",id: "639"},
    {name: "Lithuania",id: "640"},
    {name: "Luxembourg",id: "641"},
    {name: "Macau",id: "642"},
    {name: "Macedonia [FYROM]",id: "644"},
    {name: "Madagascar",id: "645"},
    {name: "Malawi",id: "646"},
    {name: "Malaysia",id: "647"},
    {name: "Maldives",id: "648"},
    {name: "Mali",id: "649"},
    {name: "Malta",id: "650"},
    {name: "Marshall Islands",id: "651"},
    {name: "Martinique",id: "652"},
    {name: "Mauritania",id: "653"},
    {name: "Mauritius",id: "654"},
    {name: "Mayotte",id: "655"},
    {name: "Mexico",id: "656"},
    {name: "Micronesia",id: "657"},
    {name: "Moldova",id: "658"},
    {name: "Monaco",id: "659"},
    {name: "Mongolia",id: "660"},
    {name: "Montenegro",id: "661"},
    {name: "Montserrat",id: "662"},
    {name: "Morocco",id: "663"},
    {name: "Mozambique",id: "664"},
    {name: "Myanmar [Burma]",id: "665"},
    {name: "Namibia",id: "666"},
    {name: "Nauru",id: "667"},
    {name: "Nepal",id: "668"},
    {name: "Netherlands",id: "669"},
    {name: "Netherlands Antilles",id: "670"},
    {name: "New Caledonia",id: "671"},
    {name: "New Zealand",id: "672"},
    {name: "Nicaragua",id: "673"},
    {name: "Niger",id: "674"},
    {name: "Nigeria",id: "675"},
    {name: "Niue",id: "676"},
    {name: "Norfolk Island",id: "677"},
    {name: "North Korea",id: "678"},
    {name: "Northern Mariana Islands",id: "679"},
    {name: "Norway",id: "680"},
    {name: "Oman",id: "681"},
    {name: "Pakistan",id: "682"},
    {name: "Palau",id: "683"},
    {name: "Palestinian Territories",id: "684"},
    {name: "Panama",id: "685"},
    {name: "Papua New Guinea",id: "686"},
    {name: "Paraguay",id: "687"},
    {name: "Peru",id: "688"},
    {name: "Philippines",id: "689"},
    {name: "Pitcairn Islands",id: "690"},
    {name: "Poland",id: "691"},
    {name: "Portugal",id: "692"},
    {name: "Puerto Rico",id: "693"},
    {name: "Qatar",id: "694"},
    {name: "Réunion",id: "695"},
    {name: "Romania",id: "696"},
    {name: "Russia",id: "697"},
    {name: "Rwanda",id: "698"},
    {name: "Saint Helena",id: "699"},
    {name: "Saint Kitts and Nevis",id: "700"},
    {name: "Saint Lucia",id: "701"},
    {name: "Saint Pierre and Miquelon",id: "702"},
    {name: "Saint Vincent and the Grenadines",id: "703"},
    {name: "Samoa",id: "704"},
    {name: "San Marino",id: "705"},
    {name: "São Tomé and Príncipe",id: "706"},
    {name: "Saudi Arabia",id: "707"},
    {name: "Senegal",id: "708"},
    {name: "Serbia",id: "709"},
    {name: "Seychelles",id: "710"},
    {name: "Sierra Leone",id: "711"},
    {name: "Singapore",id: "712"},
    {name: "Slovakia",id: "713"},
    {name: "Slovenia",id: "714"},
    {name: "Solomon Islands",id: "715"},
    {name: "Somalia",id: "716"},
    {name: "South Africa",id: "717"},
    {name: "South Georgia and the South Sandwich Islands",id: "718"},
    {name: "South Korea",id: "719"},
    {name: "Spain",id: "720"},
    {name: "Sri Lanka",id: "721"},
    {name: "Sudan",id: "722"},
    {name: "Suriname",id: "723"},
    {name: "Svalbard and Jan Mayen",id: "724"},
    {name: "Swaziland",id: "725"},
    {name: "Sweden",id: "726"},
    {name: "Switzerland",id: "727"},
    {name: "Syria",id: "728"},
    {name: "Taiwan",id: "729"},
    {name: "Tajikistan",id: "730"},
    {name: "Tanzania",id: "731"},
    {name: "Thailand",id: "732"},
    {name: "Timor-Leste",id: "733"},
    {name: "Togo",id: "734"},
    {name: "Tokelau",id: "735"},
    {name: "Tonga",id: "736"},
    {name: "Trinidad and Tobago",id: "737"},
    {name: "Tunisia",id: "738"},
    {name: "Turkey",id: "739"},
    {name: "Turkmenistan",id: "740"},
    {name: "Turks and Caicos Islands",id: "741"},
    {name: "Tuvalu",id: "742"},
    {name: "U.S. Minor Outlying Islands",id: "743"},
    {name: "U.S. Virgin Islands",id: "744"},
    {name: "Uganda",id: "745"},
    {name: "Ukraine",id: "746"},
    {name: "United Arab Emirates",id: "747"},
    {name: "United Kingdom",id: "748"},
    {name: "United States",id: "749"},
    {name: "Uruguay",id: "750"},
    {name: "Uzbekistan",id: "751"},
    {name: "Vanuatu",id: "752"},
    {name: "Vatican City",id: "753"},
    {name: "Venezuela",id: "754"},
    {name: "Vietnam",id: "755"},
    {name: "Wallis and Futuna",id: "756"},
    {name: "Western Sahara",id: "757"},
    {name: "Yemen",id: "758"},
    {name: "Zambia",id: "759"},
    {name: "Zimbabwe",id: "643"},
]

export const Regions = [
    {name: "Africa",id: "503"},
    {name: "Asia",id: "504"},
    {name: "Asia Pacific",id: "505"},
    {name: "DACH",id: "506"},
    {name: "EEA",id: "507"},
    {name: "EMEA",id: "508"},
    {name: "Europe Only",id: "509"},
    {name: "Latin America",id: "510"},
    {name: "Nordics",id: "511"},
    {name: "North America",id: "512"},
    {name: "South Asia Pacific",id: "513"},
    {name: "USA Only",id: "514"},
]